blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://totoglu.com/support
    about: We use GitHub issues only to discuss about our app and module bugs and new features.
